const express = require('express');
const router = express.Router();
const { createProject, getProjects, getProjectById, updateProject, deleteProject, getProjectTasks, getProjectSummary } = require('../controllers/projectController');
const authMiddleware = require('../middleware/authMiddleware');
router.post('/add', authMiddleware, createProject);
router.get('/', authMiddleware, getProjects);
router.get('/:id', authMiddleware, getProjectById);
router.put('/:id', authMiddleware, updateProject);
router.delete('/:id', authMiddleware, deleteProject);
router.get('/:id/tasks', authMiddleware, getProjectTasks);
router.get('/:id/summary', authMiddleware, getProjectSummary);
module.exports = router;